travis:
  secure:
    BINSTAR_TOKEN: agNZzOVjVfTP0WZMDT1iGgaxfEVI+XH019qGAu901uscdUxG5Zoflqw2jreskdJU81qPfogISRP0ehfrO+YXDkDFxRQmdeK+Mk8GHJ4N70iPf4MhKhvn4OfHpJ4778O3qcYS9mb7v8rXLQhvWjbQhMvaVUtkOyYgMxNveSDVcvX5qtOHNo11q9CVgVRoSfKKx5LQhEaOq38hkpg6bWRb2m4o8cZBy+kMLCRllOR6h7ZnPMAYhL9EANT4ymNKdjzCQysq/gT81jPmT1BTh5Vn2/CBNFj06b6FnIwGiwE9ZRlFBq1tsVEvN3IkODE5bLpGhQm68AWtBmyB75JMC2k+12v6LWK6fIqbpups+7wC/RDmr3jggQsW8PY/OcVACZH36HKsDXI7FzGxctDPyJWkckAgPpQHxCHZyCmRc8EpHpKffo/BlvmsRdSiBwjKOCtZonClPao/2IXc5b7gnacIAmD2lQC3sAtQLCLM9RMGaVLMaiWYuJCEEOZzfY5H/C4CU0/H95Ls2JlktVWiTSI9j7pSlIns/4LMgTt6kjWHhdvILCdM03iGGvA39HrHv/8IgYNc5SAWJdPeNeRhqVN/w9qDgszB7KoiX291UGDIRyy4YdU8ok2kQjxhyd/FzEyocHTwiJdffFNqlFDW0F7ds/gre3iGWQUDaG9dT3o9BZ4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
