travis:
  secure:
    BINSTAR_TOKEN: o+i6dMsJxsK6GQXACLVMO1PFyI8lEqAh5eztRSkN4olEAgHpv8f0hR5JUnMytH0vj0GM+pPuynCotKjHygA/ikE43LfCIb5tcfmYLKFafGl6F7K/1WNxFA6cLzt3ZUp0p21AijnLYsvpl0oSs3STPgvu1rAtiuan9QAF3W8xhSwG0vs9O5hYufoH4ovBtoI4ZDgj3gi84rGExooejKEdTJycVKcFLmvIID/arf2l5/7Ax9YFbe4D5nKX1qisVrd+ObD3+6qenKAjFapk9Bddy0l7xUoI0gLRkXQqMVnyEAAyQRV/LxFedtEp5WM/+yRF1+Kcu/PX7Kdm1OVPKBPp+lTaZ8Jvl4B0qj9edoxDU39kl7BtQscUWWHYkbvT5/ZeI8kkD0xGjLo0gfTLlsfkKULZU02w5WZnJV7Pdf1s/UdxJtxDPftkB46KiZjHnbAZSOOuXmtz/lgPiVN7qnW+aCH5KmY6mrA0xge+W5/uMz9zLwONE0QbbIHyf8wuwei+Fo0fNUKuA8BquAnrSg4bjnr+z8UiGLflqvFqZ/RvBJVbbD1TOHVED5eiqSTSi3lzDVjccTXcAxo26wr2S47+t8/nVaiRFei8/DYs7qvnpVn17fRlILKTcm1u3jDu4VGulnRZT5kv1JfkIPK6x91dEWSkUgBsSbIqO7EwSx5tkbs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
