travis:
  secure:
    BINSTAR_TOKEN: BUxPgsFK/aFg97Iy1KMdhXcMBQ4przzbQti6vWfEy5zD4hIBR+L7jgpZSH/9eMUKGFRV+GKPeLSgh3V6zgRiRKUlhtriQ9eKYhYLp5cZDL6HTNS4YMAQsQlcVNFURQQM8IsGxODRKb7toxV3adwdRCtH/zNONMXkUeK8Xr0aMZnS7Oz/R2gFEcO9Tf2N2KR5pUDbDYgpbCSCWuIF3vTZtLTiZWcKAqxBS6mxIhCOFP6ugqAvJSBVE5KadIvGTwkLE53aciR4Y8K13DSqp8Ew6AMKT/RDFjC5hUPTVj69vaKiPrzKu7L234kEAQSyUp2Yiurv2eMlsQMW5OKDNLN7zpzBpEzXxAajuDW6U8iieMfgO4Tw/V7/OVWh276ACgbnoxXXsXRZOzxfTvyi9FJ2/873fJUGU+iA1rZN3IFf4u1yaKXXZ+ZIOr8fuZNYcN9dhlFoTvEMEuId5uVLUXvB9h76Jgo9ELd+VIwZpnJuDnbiHd3Z63bkCwd82rLbQ6l1MOBDMIPeRznsdIZClkJo8R3pfOptMSJua0GxrMalhSuXsFxyQ9XtoiQxme8Kepa5TaKbey5bwjehYded3iln2a6+XOTBSjMkAoSkJdNdo8PvVQ6vtimpv2CuaCsCW6TxNFJJvkEoyGazr+fPeDLF3Rb06B9gKdMNAEElZjSLqLs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
