travis:
  secure:
    BINSTAR_TOKEN: KcMEtSPgDZTD1X61TdAhc7tLWhpFG/AkiKTuZACdlhDbph7byr0+8TJiCUQuWs6idA1mqyIqb9L7WZcMPBTTa39vXq08iEc2n+wMcv47925UzT2093pqIGRzRb3jp1kT5GIsouYf+5malbjqSXPKkgnHO4vvWgrvPGdfszL8QFMSaxtHLPg5rjLChCQYGtlo6Xuan8zLNvT9hopEl9UjNTBcVOQI4bt9EcpKTId1RR8AeaHYZIS48V1htanMIHe7R79DH/VVWhEk4uNliyhOQAoQk00DPJgLUP4Izqupon+y/afRaj9j4dT7echTNYgVJms/WMw7W7IEoC53w7sR2mAUsvqItb3Wu0AO7oVjGMOqtZYG/eZk++iALDTXw3aLaXIp8SG+XOJ9wihDKuKPXDb59nG2nbQAzLcWRloXYO0N9iHYYoFhgFowPpG9+BflUNKZZYJ+qEIX/jPQABIJYsGHfl18FZsH4Sj8cDgfBEhqLEmr49smK+xU2WxIGWnUuUOv6Qmd1bEA2hCwouwA/m+ACrGUB6/TxkoFt9wgdUrcdshUryRynkObswLob2LYXMMROE2S/4Sgf7ZF7/J+oa/DeSYA9IkBDTnTZ5D+mRiFCLn9GMWpnCa2llPVqSAmDtqfmjXJxbIYbGRwr0Pb+EKELVohLVBBrnO0pLCklGA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
